### ISSUE TITLE
Future of this repo

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastikrag#3]
Hello @stuarteberg,

we're currently in the process of moving our dependencies to conda-forge (as many as possible). There it is usually better to do that from the main repo, than a fork. Also our fork has diverged a bit from your repo:

![image](https://user-images.githubusercontent.com/24434157/230287997-267f6da0-1ceb-4500-bd52-693487a5120a.png)

Do you think it could make sense to transfer this repository into the ilastik org, so we can keep maintaining it there?

Cheers
Dominik

**Comment by stuarteberg** [comment]
I'm happy to transfer the repo.  I'm not sure what the appropriate procedure would be, since ilastik has its own fork of the repo.  Would you have to delete that one first?

Would it be possible to just remove the "forked from" relationship from your repo?  Then you wouldn't have to lose the repo issues and PRs.  But a brief search suggests that you'd have to contact Github support for that.

**Comment by k-dominik** [comment]
Hi @stuarteberg,

sorry for the long response time here. In the meantime I tried out the transfer thing, and it does work if the fork is renamed (which I have already done). The forking relationship stays intact, even after transfer. So I think if you like, you could just do it :)

Cheers
Dominik

**Comment by stuarteberg** [comment]
Voilà!

**Comment by k-dominik** [comment]
thank you very much @stuarteberg !
